version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Use .env for environment variables
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env  # Use .env for environment variables
    depends_on:
      - mysql

volumes:
  mysql_data:
