version: "3.8"

services:
  frontend:
    build:
      context: ./client
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # Shared environment file
    depends_on:
      - backend
    volumes:
      - ./client/public:/app/public # Static assets volume (unchanged)

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: caligo_db
      MYSQL_ROOT_PASSWORD: eric
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # MySQL data volume (unchanged)

  backend:
    build:
      context: ./Server
    dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env # Shared environment file
    volumes:
      - ./Server/uploads:/app/uploads # Uploaded images volume (unchanged)
    depends_on:
      - mysql

volumes:
  mysql_data:
