version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # Use .env for environment variables
    depends_on:
      - backend
    volumes:
      - ./client/public:/app/public # Map the frontend public folder for static assets

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: caligo_db
      MYSQL_ROOT_PASSWORD: eric
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for MySQL database
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: eric
      DB_NAME: caligo_db
      DB_PORT: 3306
    volumes:
      - ./Server/uploads:/app/uploads # Persistent storage for uploaded images in backend
    depends_on:
      - mysql

volumes:
  mysql_data: # Persistent storage for MySQL data
