version: "3.8"

networks:
  caligo_network:
    driver: bridge

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /srv/CaliGo/data/frontend_cache:/app/.next/cache
    depends_on:
      - backend
    networks:
      - caligo_network
    env_file:
      - .env # Load environment variables from .env file

  backend:
    restart: unless-stopped
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - caligo_network
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - /srv/CaliGo/data/uploads:/app/uploads # Persistent storage for user uploads

  mysql:
    restart: unless-stopped
     image: mysql:8.0
    networks:
      - caligo_network
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - /srv/CaliGo/data/mysql:/var/lib/mysql # Persistent storage for MySQL data
    ports:
      - "3307:3306"